favicon: /images/dolphin.svg

index_top_img_height: 500px
index_img: transparent

background: url(/images/default_cover.png)

theme_color:
  enable: true
  card_bg: rgba(255, 255, 255, .8)

menu:
  Home: / || fas fa-home
  Posts:
    Archives: /archives/ || fas fa-archive
    Tags: /tags/ || fas fa-tags
    Categories: /categories/ || fas fa-folder-open
  # List||fas fa-list:
  #   Music: /music/ || fas fa-music
  #   Movie: /movies/ || fas fa-video
  # Link: /link/ || fas fa-link
  # About: /about/ || fas fa-heart

aside:
  card_tags:
    color: true
  card_announcement:
    enable: false
    content: Welcome!
  card_author:
    enable: true
    description:
    button:
      enable: true
      icon: fab fa-github
      text: Follow Me
      link: https://github.com/a45s67

avatar:
  img: https://files.sakana.tw/blog/Theme/avatar-arona.png

cover:
  index_enable: true
  aside_enable: true
  archives_enable: true
  position: left
  default_cover:
    - /images/star_flower_clip.jpg

toc:
  style_simple: true

wordcount:
  enable: true
  post_wordcount: false
  min2read: true
  total_wordcount: false

post_copyright:
  enable: false

footer_bg: transparent

error_img:
  post_page: /images/crying_chopper.jpg

error_404:
  enable: true
  subtitle: "Page not found"
  background: /images/crying_chopper.jpg

comments:
  use: Giscus,Disqus

disqus:
  shortname: a45s67-blog
  lazyload: true
  count: true

giscus:
  repo: a45s67/a45s67.github.io
  repo_id: MDEwOlJlcG9zaXRvcnkyMjczMzA1OTY=
  category_id: DIC_kwDODYzKJM4CR_uz
  theme:
    light: light
    dark: dark_dimmed
  option:
    data-loading: lazy

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: butterfly

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: https://github.com/a45s67/hexo-publish-test.git
  branch: master




